name: CI

on: pull_request

jobs: 
  verify:
    name: Game Case
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install packages
      working-directory: src
      run: npm ci
    - name: Formatting, linting, tsc and tests
      working-directory: src
      run: |
        npm run prettier:check
        npm run lint
        npm run test